# Generated by Django 4.0.5 on 2022-06-20 09:07

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newspagegalleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspagegalleryimage',
            name='caption',
        ),
        migrations.AlterField(
            model_name='newspagegalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='home.homepage'),
        ),
    ]
