# Generated by Django 4.0.5 on 2022-06-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0004_remove_newspagegalleryimage_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspagegalleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='++', to='wagtailimages.image'),
        ),
    ]
